#spring:
#  datasource:
#        url: jdbc:h2:mem:testdb
#        username: leo
#        password: leo
#        driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2_console
#
